CREATE TABLE "bludo" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL
);

CREATE TABLE "howto" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "id_bludo" integer NOT NULL,
  "text" TEXT NOT NULL,
  CONSTRAINT "fk_howto_bludo_1" FOREIGN KEY ("id_bludo") REFERENCES "bludo" ("id") ON DELETE CASCADE
);

